#ifndef CHTHOLLY_TOKENTYPE_H
#define CHTHOLLY_TOKENTYPE_H

enum class TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, PERCENT,
    QUESTION, COLON,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    AND, OR,
    PLUS_PLUS, MINUS_MINUS,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
    ARROW, COLON_COLON,

    // Literals.
    IDENTIFIER, STRING, INTEGER, DOUBLE, CHAR,

    // Keywords.
    STRUCT, FUNC, LET, MUT, IF, ELSE, SWITCH, CASE, BREAK, FALLTHROUGH,
    RETURN, TRUE, FALSE, NONE, ENUM, IMPORT, PUBLIC, PRIVATE, SELF,
    TRAIT, IMPL, WHILE, FOR,

    // Special
    END_OF_FILE
};

#endif //CHTHOLLY_TOKENTYPE_H
