#ifndef CHTHOLLY_TOKENTYPE_H
#define CHTHOLLY_TOKENTYPE_H

enum class TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, SLASH, STAR, SEMICOLON,
    COLON, AMPERSAND, QUESTION,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    MINUS_GREATER,

    // Literals.
    IDENTIFIER, STRING, INTEGER, DOUBLE,

    // Keywords.
    AND, STRUCT, ELSE, FALSE, FUNC, FOR, IF, NIL, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, LET, WHILE, MUT,
    SWITCH, CASE, BREAK, FALLTHROUGH, ENUM, TRAIT, IMPL,
    IMPORT,

    EOF_TOKEN
};

#endif //CHTHOLLY_TOKENTYPE_H
